### ISSUE TITLE
proxies error

### ISSUE THREAD

**Issue by magboo** [yzyio/adidas-multi-session#11]
im getting no working proxies found result during test but when i tried on browser the proxies are working fine

**Comment by CoolA1d** [comment]
Make sure you try the same website too. Adidas blocks some proxies, especially free ones. Use the test website to test free proxies.

**Comment by bommels** [comment]
and also the max load time for 1 proxy is set to 30 seconds, if it takes longer it will skip the proxy.

**Comment by magboo** [comment]
i run test.py but getting this error
![capture](https://cloud.githubusercontent.com/assets/25304953/23136531/77b7d3e8-f79d-11e6-80c5-6db474b25add.JPG)

**Comment by zyzski** [comment]
test.py is not updated for the new version

**Comment by vladdykicks** [comment]
I'm having the same issue as OP. Proxies work fine on adidas.com through manual setup in Chrome (they're dedicated proxies from MPP). However, when I add them to the proxies.txt, the script tells me that each one of them time's out.

**Comment by F2UME** [comment]
@vladdykicks Same here now, all was working perfectly but just tried now, all proxies seem to be timing out.

**Comment by zyzski** [comment]
@EternalYZY using run.py? what PRODUCT_URL are you using?

**Comment by F2UME** [comment]
@zyzski Yes and PRODUCT_URL = 'http://tools.yzy.io/hmac.html'

**Comment by CoolA1d** [comment]
I've submitted a PR that temporarily fixes tests.py, needs more work though. 

MPP proxies should work, I plan on buying some later this week so I can test.
