### ISSUE TITLE
Crashes / fail to transfer

### ISSUE THREAD

**Issue by sailthor** [yzyio/adidas-multi-session#12]
http://i.imgur.com/VyuIhSN.png

**Comment by F2UME** [comment]
I'm just a user of the program so don't use my ideas as a guide.

I would however give a larger understanding of the issue, explain how you get these errors etc.

**Comment by sailthor** [comment]
After running and successfully checking proxies, it searches for HMAC and found by the yzy.io test it attempts to transfer. After this happens, the chrome browsers open and don't respond (force close) and this appears in cmd

**Comment by CoolA1d** [comment]
Make sure you are using [ChromeDriver 2.27](https://chromedriver.storage.googleapis.com/index.html?path=2.27/).

**Comment by F2UME** [comment]
@gt853 Even when using that, the error still persists by the way.

**Comment by vladdykicks** [comment]
Had the same issue as the original post. changed my chrome driver from 2.9 to 2.2 and it works.

**Comment by vladdykicks** [comment]
the only problem with this 2.27 chromedriver is now the Yeezy site is giving me "please update to modern browser" once the page loads

**Comment by CashHash123** [comment]
using 2.27 and receiving the same error

**Comment by PUNTxR** [comment]
I had the same issue. I tried to replace Chromedriver 2.9 with 2.2 but it still failed. Replacing with Chromedriver 2.27 resolved the problem.
