### ISSUE TITLE
Stuck at "Checking if past splash"

### ISSUE THREAD

**Issue by sc0rpion3x** [yzyio/adidas-multi-session#13]
Testing with product URL: http://www.adidas.com/us/ultraboost-uncaged-shoes/BA7997.html

Bot does not open any windows and stays checking if past splash page.

I input this URL in both the config.py and run.py

**Comment by bommels** [comment]
Make sure to download the latest version, the newest version doesnt include a config.py

**Comment by sc0rpion3x** [comment]
Thank you for your response! Greatly appreciated.

I completely deleted the folder and set up again. 

For some reason it still stays checking to see if past splash on both proxy/local IP (multiple times)

**Comment by zyzski** [comment]
@sc0rpion3x it won't pass because that page doesn't load an HMAC cookie

**Comment by sailthor** [comment]
@zyzski What is the "captcha checker" doing then?

**Comment by zyzski** [comment]
@sc0rpion3x there's no error handling on the captcha check, it just moves on to HMAC check

**Comment by sc0rpion3x** [comment]
@zyzski Oh ok. Is there a product that loads an HMAC you can point me to for testing?

**Comment by bommels** [comment]
There are currently no HMAC products online that I know of, you can use the HMAC simulate URL http://tools.yzy.io/hmac.html
