### ISSUE TITLE
Proxies won't connect, only time out.

### ISSUE THREAD

**Issue by F2UME** [yzyio/adidas-multi-session#14]
This issue is not just myself, multiple users are having the same problem.
All was working fine earlier but it now is making every proxy time out, as you can see.

It only went through using my own network without proxy as you'll see in the image..

Used both PRODUCT_URLS to test, both have same issue.

![bfy9sn8](https://cloud.githubusercontent.com/assets/25882199/23141416/a153190e-f7ae-11e6-8036-832d65d53cc7.png)

**Comment by CoolA1d** [comment]
~~It might be because you are using HTTPs proxies. Try using HTTP proxies. I don't know why HTTPs isn't supported, I will take a look later.~~

Try this one and tell me if it works:
104.207.204.200:80

You can check if a proxy is HTTP or HTTPs using [this site.](http://www.checker.freeproxy.ru/checker/)

edit: I was wrong it has nothing to do with the proxies being HTTPs, look below.

**Comment by F2UME** [comment]
Thanks for that. But the exact same proxies WERE working, I don't see why they stopped(no they aren't dead) it's relegated to this program or something, it must be..


________________________________

**Comment by CoolA1d** [comment]
@EternalYZY I think the reason is because the proxies you are using won't allow you to connect to ipecho.net/plain, which is what the bot uses to check if the proxy is working or not.

Try going into run.py and replace http://ipecho.net/plain with https://wtfismyip.com/text

**Comment by sailthor** [comment]
I find that my proxies go through the checker but when the browser opens and I check what the ip is - its my home IP not the proxy

**Comment by alaaan** [comment]
yup, i replaced ipecho with 'http://canhazip.com' and good now... MPP proxies blocked by ipecho for some reason...

**Comment by vladdykicks** [comment]
same problem as @sailthor. updated ipecho to new URL and now I pass the proxy test, but when the chrome session pops up, I go to another tab and its my original IP, not my proxy one

**Comment by bommels** [comment]
@alaaan thanks for that, didn't know ipecho blocked connections. I will create a ip returner on yzy.io to minimise the use of external services.

**Comment by bommels** [comment]
Fixed in V0.22
