### ISSUE TITLE
SORRY! YOUR BROWSER ISN'T SUPPORTED. PLEASE UPDATE TO A MODERN BROWSER.

### ISSUE THREAD

**Issue by partswd** [yzyio/adidas-multi-session#15]
Does anybody has the same issue when the chromedriver open?
![image](https://cloud.githubusercontent.com/assets/25563819/23141521/0ef5772e-f76c-11e6-9b4b-10a50e136ba6.png)

**Comment by vladdykicks** [comment]
had this issue, but it went away in subsequent reruns

**Comment by partswd** [comment]
@vladdykicks How do you slove this?
Thank you fam!!!

**Comment by CoolA1d** [comment]
Go into utils.py and replace everything in there with [this](http://pastebin.com/xei4NUsu).

**Comment by partswd** [comment]
It works!
Thanks again!!!

**Comment by zyzski** [comment]
@gt853 will you be making a PR with an updated browser list? or was it some other issue

**Comment by CoolA1d** [comment]
@zyzski I might do that later on in the week, it will be tedious having to go through them and seeing which user-agents are good and which aren't. Idk why bommels didn't just stick with one user-agent, but it probably has some meaning behind it.

**Comment by PUNTxR** [comment]
I had this issue as well. Replacing utils.py resolved the problem.

**Comment by bommels** [comment]
Fixed in V0.22
