### ISSUE TITLE
Proxy IP on Chrome not working

### ISSUE THREAD

**Issue by lucidhyped** [yzyio/adidas-multi-session#18]
Hello all!

everything seems to be working fine, but my question is once chromedriver opens up in a session. when i try to go to ipecho.net to check if i'm logged in one of my proxies in the chrome session it still shows my host ip. does that mean i'm not logged in through proxies and just my reg ip ?

**Comment by sailthor** [comment]
Same here. : c

**Comment by bommels** [comment]
This is a known issue, I will be looking into it.

**Comment by bommels** [comment]
Fixed in V0.22
