### ISSUE TITLE
Proxies do not work

### ISSUE THREAD

**Issue by F2UME** [yzyio/adidas-multi-session#19]
Hi
So when the proxy is transfered and then open in chrome. if you check the IP address of the sessions, the IP addresses are all your real IPs when checking. what's this all about? 

![w0ugx8u](https://cloud.githubusercontent.com/assets/25882199/23192529/dfc004f2-f89b-11e6-86bb-2556d4729bdc.png)

**Comment by bommels** [comment]
Will check this out, thanks

**Comment by txsneakerhead23** [comment]
I get the same issue the proxy does not transfer over.

**Comment by Asteezy24** [comment]
this happened to me as well

**Comment by bommels** [comment]
Fixed in V0.22
