### ISSUE TITLE
proxies not working

### ISSUE THREAD

**Issue by iConfigurator** [yzyio/adidas-multi-session#2]
don't know what's wrong but whenever I paste in my proxies.

I'm inputing them like this
ip:port, usr:pass

am I typing them wrong or are my settings messed up? 

Not sure what's going on

**Comment by T3RRORTOAST** [comment]
I have the same problem, I putting them in like:
(ip:port, usr:pass),
(ip:port, usr:pass),
(ip:port, usr:pass),
(ip:port, usr:pass)

**Comment by Lunier** [comment]
You have to put your ip:port between ''
Example:
('ip:port',None)

**Comment by T3RRORTOAST** [comment]
Thanks for the answer, and what is about the password? Should it be like this:

('ip:port','usr:pw'),
('ip:port','usr:pw'),
('ip:port','usr:pw'),
('ip:port','usr:pw')


?

**Comment by Lunier** [comment]
if you get a syntax error i would say yes.

**Comment by iConfigurator** [comment]
it works but now whenever I enter more than one proxy i get a syntax error "TypeError: 'tuple' object is not callable"
