### ISSUE TITLE
Chromedriver remote end closed connection without response

### ISSUE THREAD

**Issue by ghost** [yzyio/adidas-multi-session#20]
![screen shot 2017-02-21 at 11 19 55 pm](https://cloud.githubusercontent.com/assets/25945191/23197187/93eec130-f88c-11e6-946a-0d1509586ec7.png)

**Comment by ghost** [comment]
![screen shot 2017-02-22 at 1 57 19 am](https://cloud.githubusercontent.com/assets/25945191/23200432/50edb344-f8a2-11e6-83a6-3212d3160f90.png)

**Comment by bommels** [comment]
Try an other chromedriver version, tests.py is not updated yet.

**Comment by ghost** [comment]
2.27 worked thanks!
