### ISSUE TITLE
Issue starting script

### ISSUE THREAD

**Issue by CitrineExcalbur** [yzyio/adidas-multi-session#22]
![adidasmultierror](https://cloud.githubusercontent.com/assets/6341641/23244332/03d73eba-f94a-11e6-9ff1-9a4514c4b22c.png)

I've uninstalled and reinstalled all of the files necessary, and continue to get this error. Is there anything else I can try? I'm sure it's something simple I'm overlooking...

**Comment by bommels** [comment]
phantomjs can not be found, make sure to download the latest adidas-multi-session version (0.22 atm) and put the phantomjs.exe and chromedriver.exe in the parent folder.
