### ISSUE TITLE
Captcha Error

### ISSUE THREAD

**Issue by nikevp** [yzyio/adidas-multi-session#26]
Currently I'm unable to solve captcha once the chromedriver session launches.  I can click all the captcha tiles, but clicking verify makes it ask for a new solve ("please try again").

**Comment by F2UME** [comment]
What captcha are you talking about.. where?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by nikevp** [comment]
On an adidas product page that I was using to test.

**Comment by F2UME** [comment]
What is the URL.

**Comment by nikevp** [comment]
http://www.adidas.com/us/pureboost-ltd-shoes/S80701.html

**Comment by nikevp** [comment]
I also tried another URL.  I solve it and click verify but it acts like I failed the solve. (obv need the recaptcha response to cart)

**Comment by F2UME** [comment]
@nikevp I've just tested, it must be your proxies.

**Comment by nikevp** [comment]
I don't think that's the issue, I tested multiple proxies from multiple sources

**Comment by bommels** [comment]
Google / Recaptcha can ban your proxies. Can you open console (F12) and see if there are any errors?

**Comment by nikevp** [comment]
Will do

**Comment by alaaan** [comment]
when i change a product url to a product on ADC with captcha on it (like URL above), the script is not opening any sessions? Anyone else?

**Comment by PUNTxR** [comment]
I was able to recreate this issue using http://www.adidas.com/us/pureboost-ltd-shoes/S80701.html as the product. The captcha loads but doesn't behave normally. It loads slow and sometimes images are blank boxes. I tried the same proxies manually in another browser and there was no issue. I didn't see any errors in console. WIN10, Chromedriver 2.27

**Comment by alaaan** [comment]
weird, mine doesnt even trigger to open up the session in chrome

**Comment by alaaan** [comment]
ok so ill figure out my issue next, but i just put current yeezy page back in, hit the HMAC and opened up the browser. I navigated to the URL above and I'm having same issues solving captcha... hmmm

**Comment by alaaan** [comment]
might be in trouble here...  Something is flagging it. If you switch to audio captcha, it sends you to this page http://google.com/recaptcha/securityhelp

**Comment by alaaan** [comment]
i definitely think there is some sort of detection of selenium / web driver... Try stubhub.com and you'll likely be blocked...

**Comment by nikevp** [comment]
Yeah it's definitely not proxys

**Comment by alaaan** [comment]
ill let @bommels chime in here... 

I tried excplicitly defining these two phantomjs settings. Although they are supposed to be the default, since adding this i can't recreate the slow/unresponsive captcha. 

`desired_capabilities['phantomjs.page.settings.javascriptEnabled'] = True
    desired_capabilities['phantomjs.page.settings.loadImages'] = True`

**Comment by txsneakerhead23** [comment]
when I use one the proxies I bought from MPP chromedriver crashes and I get this error 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ken/Desktop/adidas-multi-session-master/bot.py", line 41, in transfer_session
    chrome.add_cookie(cookie)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium-3.0.2-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 671, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium-3.0.2-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium-3.0.2-py3.5.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: <unknown>: Failed to set the 'cookie' property on 'Document': Cookies are disabled inside 'data:' URLs.
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.11.6 x86_64)

**Comment by txsneakerhead23** [comment]
okay i don't get the error no more when i authenticate my ip so i guess it has problems with user/pass proxies.

**Comment by nikevp** [comment]
Update: I think it is a proxy and browser combination deal.  It is weird because sometimes I can just refresh and it will work but others nothing fixes that particular browser

**Comment by nikevp** [comment]
I think we can close this issue. After a lot of testing ect it appears to be primarily proxy based.  I don't think it is permanent on most because I'd get through once, but then I was unable to solve anymore.
