### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by ccarley** [yzyio/adidas-multi-session#28]
This is my first time using python and i'm having trouble running "pip install -r requirements.txt", so could I get some advice. Thanks

**Comment by nikevp** [comment]
You need to direct your terminal or CMD into the folder first. For example if the bot is on your desktop the commands would be: cd Desktop/insert_folder (desktop/adidasbot).  Then run the pip command

**Comment by ccarley** [comment]
Thanks but it keeps saying "The system cannot find the path specified."

**Comment by nikevp** [comment]
Are you on Mac?

**Comment by ccarley** [comment]
no windows

**Comment by nikevp** [comment]
Save the bot to your desktop, make sure it is only in one folder not two. and tell me what the name of  the folder is.

**Comment by ccarley** [comment]
by bot do you mean the repository clone of the file within the clone named "bot"?

**Comment by ccarley** [comment]
or**

**Comment by nikevp** [comment]
the folder containing all the files

**Comment by nikevp** [comment]
which by default is called 'adidas-multi-session'

**Comment by ccarley** [comment]
yes i named it "adidas-multi-session-master"

**Comment by nikevp** [comment]
ok so commands:

1) Enter: cd desktop/adidas-multi-session-master
2) pip install -r requirements.txt

if that isnt working you have another folder in the 'adidas-multi-session-master' before the files you want to access.

If that is the case new command: cd desktop/adidas-multi-session-master/(additional folder name)

**Comment by ccarley** [comment]
and i type that into python right?

**Comment by nikevp** [comment]
Ah thats your issue, no you dont start python at all during this

**Comment by ccarley** [comment]
oh ok lol so just into cmd?

**Comment by ccarley** [comment]
Now im getting, 'pip' is not recognized as an internal or external command,
operable program or batch file. Thanks alot for the help btw

**Comment by ccarley** [comment]
ok i got it i had to add "py -m pip" in front of the command and now it worked
