### ISSUE TITLE
Proxy Connection

### ISSUE THREAD

**Issue by jassingh9** [yzyio/adidas-multi-session#31]
Hi there,
So when I use the proxy on Chrome with a plugin to connect to Adidas.com it works perfectly fine. But then when I use the exact same proxy on the script it times out when it tries to connect to the site I specified which is Adidas.com
Any thing I can do to fix it?
Thanks

**Comment by bommels** [comment]
It times out at 30 seconds, are you sure your proxy is fast enough?
