### ISSUE TITLE
proxy timing out

### ISSUE THREAD

**Issue by ed-biz23** [yzyio/adidas-multi-session#32]
Anyone having problem with proxy time out, even though it works when i use the proxy to other bot or on my chrome browser?

**Comment by jassingh9** [comment]
I'm having the same issue.

**Comment by ccarley** [comment]
Have the same problem

**Comment by ellenzhuwang** [comment]
same issue

**Comment by tehisaac** [comment]
test your proxies, adidas banned a whole lot before EU drop

**Comment by bommels** [comment]
Also test them on speed because the time-out is 30 seconds

**Comment by bommels** [comment]
Proxy testing will be optional in new version
