### ISSUE TITLE
UK drop

### ISSUE THREAD

**Issue by CashHash123** [yzyio/adidas-multi-session#36]
For UK drop script simply opened chrome to live splash page.  Splash wasnt keep in phantomjs

**Comment by sailthor** [comment]
There was a useless HMAC hanging out on their splash page to combat bots. Meant that multi session picked up the HMAC and was under the impression we were at the product page

**Comment by bommels** [comment]
This has been fixed in the latest version, not in time for EU unfortunately. Script only checks for captcha now.
