### ISSUE TITLE
Huge issue running the bot today

### ISSUE THREAD

**Issue by iConfigurator** [yzyio/adidas-multi-session#4]
Almost every single one of my sessions timed out. All 22 of my proxies timed out, and I know they aren't banned because I just tested all of them.

**Comment by bommels** [comment]
It waits 20s for the page to load, are your proxies fast?

**Comment by iConfigurator** [comment]
Not sure. But every 30 seconds I would get a session timed out message. took like 10 minutes to go through all of my proxies just to tell me my session timed out.

**Comment by bommels** [comment]
are you using proxies with authentication?

**Comment by iConfigurator** [comment]
yep

**Comment by bommels** [comment]
New version includes proxy testing, please try and make a new issue if you run into an issue.
