### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by pfcpinto** [yzyio/adidas-multi-session#7]
When I run the script with 2 proxies loaded. I get "session started: looking for hmac etc" When i load all 100 proxies and run it i get no errors but just a "blinking _" after it says url valid. Is that normal or should it label out all sessions like it does with just two proxies?

**Comment by bommels** [comment]
update improving speed coming soon, however that's not normal behaviour. If a proxy can't be loaded it should time-out in 30s.
