### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by owenhalpert** [yzyio/adidas-multi-session#9]
<img width="1280" alt="screen shot 2017-02-19 at 10 00 12 am" src="https://cloud.githubusercontent.com/assets/22207516/23104856/53ea16e2-f68a-11e6-8cb7-749a8e9b6784.png">

get this error. already added chromedriver and phantomjs to my paths, not sure whats wrong

**Comment by bommels** [comment]
hi, do you have the phantomjs file in the same folder as the script? (same folder as run.py).

**Comment by owenhalpert** [comment]
<img width="791" alt="screen shot 2017-02-19 at 10 04 48 am" src="https://cloud.githubusercontent.com/assets/22207516/23104879/e6f10c16-f68a-11e6-8c61-594ccac1661e.png">
Yes, is this correct?

**Comment by bommels** [comment]
If you change line 53 of file run.py:
> browser = webdriver.PhantomJS(service_args=service_args, desired_capabilities=desired_capabilities)

to

> browser = webdriver.PhantomJS(executable_path='', service_args=service_args, desired_capabilities=desired_capabilities)

Does that work?

**Comment by owenhalpert** [comment]
<img width="1280" alt="screen shot 2017-02-19 at 10 14 59 am" src="https://cloud.githubusercontent.com/assets/22207516/23104953/4af60dd2-f68c-11e6-9ea4-90e13d1effdf.png">

**Comment by bommels** [comment]
And if you do

> browser = webdriver.PhantomJS(executable_path='phantomjs', service_args=service_args, desired_capabilities=desired_capabilities)

If that doesnt work try setting it to the absolute location of the phantomjs file (ex /Users/user/Documents etc)

**Comment by owenhalpert** [comment]
<img width="1280" alt="screen shot 2017-02-19 at 10 22 09 am" src="https://cloud.githubusercontent.com/assets/22207516/23105010/492374e4-f68d-11e6-9447-c3eb00147b75.png">

After changing line 53 to 

> browser = webdriver.PhantomJS(executable_path='/users/owenhalpert/documents', service_args=service_args, desired_capabilities=desired_capabilities)

**Comment by bommels** [comment]
Try placing phantomjs in a folder called bin (in the run.py folder)

> webdriver.PhantomJS(executable_path='bin/phantomjs', service_args=service_args, desired_capabilities=desired_capabilities)

**Comment by owenhalpert** [comment]
Got rid of the phantomjs problem but...

<img width="1280" alt="screen shot 2017-02-19 at 10 26 00 am" src="https://cloud.githubusercontent.com/assets/22207516/23105053/d87ac714-f68d-11e6-85be-3155d1635e91.png">

Is this just because I haven't put any real proxies in yet?

**Comment by bommels** [comment]
Phantom shouldnt have issues with proxies. This is a problem because you removed line 

> webdriver.PhantomJS(executable_path='bin/phantomjs', service_args=service_args, desired_capabilities=desired_capabilities)

I think

**Comment by owenhalpert** [comment]
Should I put phantom into that exact path and just change that line back?

**Comment by bommels** [comment]
Try this one:
https://github.com/yzyio/adidas-multi-session/issues/9#issuecomment-280937644

**Comment by owenhalpert** [comment]
That's what it is currently, gives me that browser issue.

**Comment by bommels** [comment]
> browser = webdriver.PhantomJS(executable_path='bin/phantomjs', service_args=service_args, desired_capabilities=desired_capabilities)

**Comment by owenhalpert** [comment]
Thanks. Your code worked but I had to change 'bin/phantomjs' to '/bin/phantomjs' 👍

**Comment by bommels** [comment]
Ok perfect, I will push an update for this soon. Make sure to also change Line 29 of bot.py to:

> chrome = webdriver.Chrome(executable_path='/bin/chromedriver', chrome_options=chrome_options)

**Comment by magboo** [comment]
hi how can i put proxy without username and pw?? getting error when i tested it i just put none@host:port

**Comment by CoolA1d** [comment]
@magboo just put host:port

**Comment by magboo** [comment]
im getting no working proxies result but proxies are working on browser when i tried it
